version: '3'

services:
  tankobon-server:
    build: ./
    volumes:
      - ./test/manga:/opt/app/manga
      - ./test/data:/opt/app/data
      - ./tankobon-config.yml:/opt/app/tankobon-config.yml
    ports:
      - "8080:8080"
