version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  tankobon-server:
    build: ./
    volumes:
      - ./test/content:/opt/app/content
      - tankobon-data:/opt/app/data
      - ./tankobon-config.yml:/opt/app/tankobon-config.yml
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    links:
      - postgres

volumes:
  postgres:
  tankobon-data:
