server:
  title: "Tankōbon"
  description: "Tankōbon instance with some cool manga"
  user: "user"
  password: "password"
  logFile: "./data/logfile.log"
  logLevel: "INFO" # INFO, WARN, DEBUG, TRACE

database:
  url: "jdbc:postgresql://postgres:5432/postgres"
  user: "postgres"
  password: "password"
  schema: "tankobon"
  bcryptRounds: 12

api:
  address: "0.0.0.0"
  port: 8080
  expire:
    # milliseconds
    # 0 - infinite
    access: 86400000
    refresh: 1209600000

library:
  content: "./content"
  data: "./data"
