name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '*.md'

env:
  DOCKER_HUB: acetylsalicylicacid/${{ github.event.repository.name }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    uses: ./.github/workflows/docker-publish.yml
