name: Build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '*.md'


jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build
    uses: ./.github/workflows/docker-publish.yml
